analysis/urls.py
from django.urls import path
from . import views

app_name = "analysis"

urlpatterns = [
    path('', views.show_analysis, name='analysis'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
import index.views
import topic.views
import voice.views
import analysis.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index.views.index, name='index'),
    path('topic/', include('topic.urls')),
    path('analysis/', include('analysis.urls')),
    path('voice/', include('voice.urls')),
]

topic/urls.py
from django.urls import path
from . import views

app_name = "topic"

urlpatterns = [
    path('', views.show_topic, name='topic'),
]

voice/urls.py
from django.urls import path
from . import views

app_name = "voice"

urlpatterns = [
    path('', views.get_voice, name='voice'),
]

analysis/models.py
from django.db import models

# Create your models here.

index/models.py
from django.db import models

# Create your models here.

topic/models.py
from django.db import models

# class BigTopic(models.Model):
#     id = models.BigAutoField(help_text="BigTopic ID", primary_key=True)
#     bigTopic = models.CharField(max_length=20, blank=False, null=False)
#
# class SmallTopic(models.Model):
#     id = models.BigAutoField(help_text="SmallTopic ID", primary_key=True)
#     smallTopic = models.ManyToManyField('BigTopic',blank=False)

class Question(models.Model):
    question_text = models.CharField(max_length=200)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

    def __str__(self):
        return self.choice_text

voice/models.py
from django.db import models

# Create your models here.

analysis/views.py
from django.shortcuts import render


def show_analysis(request):
    return render(request, 'show_anaylsis.html')

index/views.py
from django.shortcuts import render

def index(request):
    return render(request,'index.html')

topic/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question
from .models import Choice

def show_topic(request):
    topics = Question.objects
    choices = Choice.objects
    choices_friends = Choice.objects.filter(question_id=1)
    choices_love = Choice.objects.filter(question_id=3)
    print("topics: {}".format(topics))
    print("choice: {}".format(choices))
    return render(request, 'show_topic.html', {'topics': topics, 'choices': choices, 'choices_friends':choices_friends, 'choices_love':choices_love})

voice/views.py
from django.shortcuts import render


def get_voice(request):
    return render(request, 'get_voice.html')

analysis/templates/show_anaylsis.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
{% endblock %}

{% block content %}
    <div class="tit-analysis">
        <span>Your text</span>
        <span>Frequency</span>
    </div>
    <div class="contents-analysis">
        <div class="usertext">
            어 저의 가장 친한 친구는 냐옹이에요. <br><br>
            음 길가다 우연히 마주쳤어요. <br><br>
            완전 운명인 것 같았는데... <br><br>
            음 지나고 보니 아니었던 것 같아요. <br><br>
        </div>
        <div class="frequency">
            <canvas id="myChart"></canvas>
        </div>
    </div>
    <div class="btn-nextprev">
        <button class="prev"><a href="{% url 'voice:voice' %}">Prev</a></button>
        <button class="save"><a href="#">Save</a></button>
    </div>

    <script src="{% static 'analysis/analysis.js' %}" ></script>
{% endblock %}

index/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="contents-start">
        <img src="{% static 'project/talking.svg' %}">
        <p>원활한 대화 및 자신감을 향상시키기 원하신다면 지금 바로 시작해보세요!</p>
        <button class="btn-start"><a href="{% url 'topic:topic' %}">START</a></button>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="data:;base64,iVBORw0KGgo=">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'project/style.css' %}">

    <script
      src="https://code.jquery.com/jquery-3.6.0.js"
      integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
      crossorigin="anonymous"></script>
    <title>BASE</title>
    <script type="text/javascript" src="http://code.jquery.com/jquery.js"></script>
    {% block header %}

    {% endblock %}
</head>
<body>
    <nav>
        <p class="logo"><a href="{% url 'index' %}">GREATE TALKER!!!!</a></p>
        <div class="nav-bar">
            <p><a href="{% url 'topic:topic' %}">Topic</a></p>
            <p><a href="{% url 'voice:voice' %}">Voice</a></p>
            <p><a href="{% url 'analysis:analysis' %}">Analysis</a></p>
            <i class="fas fa-bars fa-lg"></i>
        </div>
    </nav>

    <div class="contents">
        {% block content %}


        {% endblock %}
    </div>


</body>
</html>

topic/templates/show_topic.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="contents-topic">
        <select class="topic-big invisible-scrollbar" name="mainCategory" style="width:400px; height:320px" multiple="multiple">
        </select>

        <i class="fas fa-caret-right"></i>

        <select class="topic-small invisible-scrollbar" name="subCategory" style="width:600px; height:320px" multiple="multiple">
        </select>
    </div>
    <!--multiple을 쓰면 다 보여주고 없으면 드롭다운으로 선택할 수 있음-->
    <!--키워드로 css select 꾸미기 찾아보면 될듯-->


    <div class="btn-nextprev">
        <button class="prev"><a href="{% url 'index' %}">Prev</a></button>
        <button class="next"><a href="{% url 'voice:voice' %}">Next</a></button>
    </div>

    <script src="{% static 'topic/topic.js' %}" ></script>

{% endblock %}

voice/templates/get_voice.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="contents-upload">
        <div class="upload-record">
            <input type=checkbox id="chk-hear-mic"><label for="chk-hear-mic">마이크 소리 듣기</label>
            <button id="record">녹음</button>
            <button id="stop">정지</button>
            <div id="sound-clips"></div>
        </div>
        <div class="upload-file">
            <p>Drag & Drop to Upload File</p>
            <p>OR</p>
            <button class="select-file">파일 선택</button>
            <input type="file" hidden>
        </div>
    </div>

    <div class="btn-nextprev">
        <button class="prev"><a href="{% url 'topic:topic' %}">Prev</a></button>
        <button class="next"><a href="{% url 'analysis:analysis' %}">Next</a></button>
    </div>

    <script src="{% static 'voice/voice.js' %}" ></script>
{% endblock %}

voice/templates/mic.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>마이크 테스트</title>
</head>

<body>
    <input type=checkbox id="chk-hear-mic"><label for="chk-hear-mic">마이크 소리 듣기</label>
    <button id="record">녹음</button>
    <button id="stop">정지</button>
    <div id="sound-clips"></div>
    <script>
        const record = document.getElementById("record")
        const stop = document.getElementById("stop")
        const soundClips = document.getElementById("sound-clips")
        const chkHearMic = document.getElementById("chk-hear-mic")

        const audioCtx = new(window.AudioContext || window.webkitAudioContext)() // 오디오 컨텍스트 정의

        const analyser = audioCtx.createAnalyser()
        //        const distortion = audioCtx.createWaveShaper()
        //        const gainNode = audioCtx.createGain()
        //        const biquadFilter = audioCtx.createBiquadFilter()

        function makeSound(stream) {
            const source = audioCtx.createMediaStreamSource(stream)

            source.connect(analyser)
            //            analyser.connect(distortion)
            //            distortion.connect(biquadFilter)
            //            biquadFilter.connect(gainNode)
            //            gainNode.connect(audioCtx.destination) // connecting the different audio graph nodes together
            analyser.connect(audioCtx.destination)

        }

        if (navigator.mediaDevices) {
            console.log('getUserMedia supported.')

            const constraints = {
                audio: true
            }
            let chunks = []

            navigator.mediaDevices.getUserMedia(constraints)
                .then(stream => {

                    const mediaRecorder = new MediaRecorder(stream)
                    
                    chkHearMic.onchange = e => {
                        if(e.target.checked == true) {
                            audioCtx.resume()
                            makeSound(stream)
                        } else {
                            audioCtx.suspend()
                        }
                    }
                    
                    record.onclick = () => {
                        mediaRecorder.start()
                        console.log(mediaRecorder.state)
                        console.log("recorder started")
                        record.style.background = "red"
                        record.style.color = "black"
                    }

                    stop.onclick = () => {
                        mediaRecorder.stop()
                        console.log(mediaRecorder.state)
                        console.log("recorder stopped")
                        record.style.background = ""
                        record.style.color = ""
                    }

                    mediaRecorder.onstop = e => {
                        console.log("data available after MediaRecorder.stop() called.")

                        const clipName = prompt("오디오 파일 제목을 입력하세요.", new Date())

                        const clipContainer = document.createElement('article')
                        const clipLabel = document.createElement('p')
                        const audio = document.createElement('audio')
                        const deleteButton = document.createElement('button')

                        clipContainer.classList.add('clip')
                        audio.setAttribute('controls', '')
                        deleteButton.innerHTML = "삭제"
                        clipLabel.innerHTML = clipName

                        clipContainer.appendChild(audio)
                        clipContainer.appendChild(clipLabel)
                        clipContainer.appendChild(deleteButton)
                        soundClips.appendChild(clipContainer)

                        audio.controls = true
                        const blob = new Blob(chunks, {
                            'type': 'audio/ogg codecs=opus'
                        })
                        chunks = []
                        const audioURL = URL.createObjectURL(blob)
                        audio.src = audioURL
                        console.log("recorder stopped")

                        deleteButton.onclick = e => {
                            evtTgt = e.target
                            evtTgt.parentNode.parentNode.removeChild(evtTgt.parentNode)
                        }
                    }

                    mediaRecorder.ondataavailable = e => {
                        chunks.push(e.data)
                    }
                })
                .catch(err => {
                    console.log('The following error occurred: ' + err)
                })
        }
    </script>
</body></html>